version: '3.5'

services:
  reformiqo-erp-frontend:
    container_name: reformiqo-erp-frontend
    image: ${REGISTRY_URL}/${IMAGE_NAME}:${TAG_VERSION:-latest}
    ports:
      - "80:$PORT"
    enviroments:
      - TAG_VERSION
      - PORT
      - REGISTRY_URL
      - IMAGE_NAME
      - NODE_ENV
      - REDIRECT_TO_HTTPS
      - UNDER_MAINTENANCE_MODE
      - APP_LOCATION
      - API_URL
      - API_PREFIX
      - API_VERSION