version: '3.5'

services:
  reformiqo-erp-frontend:
    image: reformiqo-erp-ui:latest
    container_name: reformiqo-erp-ui
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./proxy-server/.env
