name: Build and Deploy

on: [workflow_dispatch]

jobs:
  
  build:
    environment: Dev
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Declare vars
      id: vars
      run: echo "build_image_tag=${{ secrets.ENV_NAME }}-${GITHUB_RUN_NUMBER}-$(echo ${GITHUB_SHA} | cut-c1-8)" >> $GITHUB_OUTPUT
    
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.output.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.vars.outputs.build_image_tag }} -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ secrets.IMAGE_TAG }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

        # docker build -t $ECR_REPOSITORY .
        # docker tag $ECR_REGISTRY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
        # docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
    
    - name: Deploy
      run: zip -r "deploy.zip" docker-compose.yml

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.ENV_NAME }}
        version_label: ${{ steps.vars.outputs.build_image_tag }}
        region: us-east-1
        deployment_package: deploy.zip